baseURL = '/'
languageCode = 'ca-es'
title = 'CV - Lluís Noval'
theme = 'almeida-cv'

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
footerNote = "2025 © by Lluís Noval Juanola"
